"""RRC-framed full-deliberation training targets (the ``framed_deliberation`` condition).

For HARD vignettes we want the SFT target chain-of-thought to be an RRC
*procedure-selection* preamble ("this case is high-stakes/unusual, so I'll
simulate rational bargaining rather than apply a rule") followed by the FULL
virtual-bargaining deliberation from the paper's VB sheet, **verbatim**.

Only the short preamble is written by a cheap LLM (see ``PREAMBLE_PROMPT``).
Row selection, the YES/NO answer, and the ``preamble + VB body`` concatenation
are deterministic code here, so the LLM never touches the VB deliberation or the
answer (which would risk a CoT whose stated conclusion contradicts START_OUTPUT).

The LLM's preambles are committed to :data:`SIDECAR_PATH` -- that JSON is the
reproducibility anchor, because ``data/`` is git-ignored and regenerated by the
pipeline. :func:`load_framed` reads the sidecar and re-verifies each story
against the workbook; ``datasets_common.load_condition("framed_deliberation")``
applies the result.

This module reads the workbooks with a dependency-free stdlib xlsx reader so the
one-off build step (and the story-checksum verification at pipeline time) need
neither pandas nor openpyxl.
"""

from __future__ import annotations

import json
import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

# Single source of truth for which model / files supply the deliberations.
MODEL = "DeepSeek-R1"
HARD_FILES = [
    ("agent", "hard", "agent_hard_cases.xlsx"),
    ("development", "hard", "development_hard_cases.xlsx"),
]

SIDECAR_PATH = Path(__file__).resolve().parent.parent / "assets" / "framed_deliberation.json"

_NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
_RNS = "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}"


# --- dependency-free xlsx reader ---------------------------------------------
def _col_to_idx(ref: str) -> int:
    letters = re.match(r"[A-Z]+", ref).group(0)
    idx = 0
    for ch in letters:
        idx = idx * 26 + (ord(ch) - 64)
    return idx - 1


def _read_sheet(path: Path, sheet: str) -> list[dict]:
    """Return the sheet's data rows as list[dict] keyed by header name.

    Row order and header handling match pandas ``read_excel`` (header = first
    row, data rows follow), so the positional ``row_index`` used as the sidecar
    key is identical to ``iloc[i]`` in ``datasets_common.load_sheet``.
    """
    z = zipfile.ZipFile(path)
    shared: list[str] = []
    if "xl/sharedStrings.xml" in z.namelist():
        root = ET.fromstring(z.read("xl/sharedStrings.xml"))
        for si in root.findall(f"{_NS}si"):
            shared.append("".join(t.text or "" for t in si.iter(f"{_NS}t")))
    wb = ET.fromstring(z.read("xl/workbook.xml"))
    rels = ET.fromstring(z.read("xl/_rels/workbook.xml.rels"))
    rid2tgt = {r.get("Id"): r.get("Target") for r in rels}
    name2file = {}
    for s in wb.find(f"{_NS}sheets"):
        tgt = rid2tgt[s.get(f"{_RNS}id")]
        name2file[s.get("name")] = tgt if tgt.startswith("xl/") else "xl/" + tgt
    if sheet not in name2file:
        raise KeyError(f"sheet {sheet!r} not in {path.name}: {list(name2file)}")

    # Rows are appended in document order and their `r` index is not consulted;
    # this matches pandas read_excel for these dense workbooks. The story-checksum
    # assert in load_condition catches any divergence before it can misalign.
    root = ET.fromstring(z.read(name2file[sheet]))
    raw_rows = []
    for row in root.find(f"{_NS}sheetData").findall(f"{_NS}row"):
        cells = {}
        for c in row.findall(f"{_NS}c"):
            ci = _col_to_idx(c.get("r"))
            t = c.get("t")
            v = c.find(f"{_NS}v")
            isv = c.find(f"{_NS}is")
            if t == "s" and v is not None:
                cells[ci] = shared[int(v.text)]
            elif t == "inlineStr" and isv is not None:
                cells[ci] = "".join(x.text or "" for x in isv.iter(f"{_NS}t"))
            elif v is not None:
                cells[ci] = v.text
            else:
                cells[ci] = ""
        raw_rows.append(cells)
    if not raw_rows:
        return []
    header = {(v or "").strip(): i for i, v in raw_rows[0].items()}
    return [{name: (r.get(i, "") or "") for name, i in header.items()} for r in raw_rows[1:]]


def _acc1(v) -> bool:
    try:
        return float(v) == 1.0
    except (TypeError, ValueError):
        return str(v).strip() in ("1", "1.0", "True", "TRUE")


# --- extraction (used by the one-off build step) -----------------------------
def selected_hard_vb(results_dir: str | Path) -> list[dict]:
    """The hard VB traces that get framed: accuracy==1 and non-empty reasoning.

    Emptiness is enforced here (and mirrored in ``load_condition``) so the
    sidecar never has to cover rows that ``prepare_data`` would later drop.
    """
    results_dir = Path(results_dir)
    out = []
    for domain, difficulty, fname in HARD_FILES:
        rrc = _read_sheet(results_dir / fname, f"{MODEL} RRC")
        vb = _read_sheet(results_dir / fname, f"{MODEL} VB")
        assert len(rrc) == len(vb), f"row count mismatch in {fname}"
        for i in range(len(vb)):
            assert rrc[i].get("Prompts", "") == vb[i].get("Prompts", ""), (
                f"RRC/VB story misaligned at row {i} in {fname}"
            )
            if not _acc1(vb[i].get("accuracy", "")):
                continue
            if not vb[i].get("reasoning", "").strip():
                continue
            out.append(
                {
                    "id": f"{domain}|{difficulty}|{i}",
                    "domain": domain,
                    "difficulty": difficulty,
                    "row_index": i,
                    "story": vb[i].get("Prompts", ""),
                    "rrc_reasoning": rrc[i].get("reasoning", ""),
                    "vb_reasoning": vb[i].get("reasoning", ""),
                    "vb_answer": str(vb[i].get("output", "")).strip().upper(),
                }
            )
    return out


def build_framed_reasoning(preamble: str, vb_reasoning: str) -> str:
    """Assemble the final target CoT. VB body is used verbatim."""
    return preamble.strip() + "\n\n" + vb_reasoning.strip()


def sidecar_key(domain: str, difficulty: str, row_index: int) -> str:
    return f"{domain}|{difficulty}|{row_index}"


# --- loading (used by datasets_common.load_condition) ------------------------
def load_framed(results_dir: str | Path) -> dict[str, tuple[str, str]]:
    """Map ``sidecar_key`` -> ``(framed_reasoning, story)``, verifying coverage.

    The row-index key is deterministic; the returned story lets the caller assert
    the row it splices onto (read with pandas) matches the row this sidecar was
    built from (read with the stdlib reader). Also tripwires a stale sidecar.
    """
    if not SIDECAR_PATH.exists():
        raise FileNotFoundError(
            f"framed_deliberation sidecar missing: {SIDECAR_PATH}. "
            "Rebuild it with scripts/build_framed_sidecar.py."
        )
    sidecar = json.loads(SIDECAR_PATH.read_text())
    live = {row["id"]: row["story"] for row in selected_hard_vb(results_dir)}
    framed = {}
    for key, entry in sidecar.items():
        assert key in live, f"sidecar key {key} no longer selected from workbooks"
        assert entry["story"] == live[key], f"story checksum mismatch for {key}"
        framed[key] = (build_framed_reasoning(entry["preamble"], entry["vb_reasoning"]), entry["story"])
    missing = set(live) - set(framed)
    assert not missing, f"sidecar missing {len(missing)} selected rows, e.g. {sorted(missing)[:3]}"
    return framed


# --- LLM instructions (documents how the committed preambles were produced) --
PREAMBLE_PROMPT = """You write the OPENING of a moral chain-of-thought.

You are given a moral dilemma (`story`) and a prior reasoning trace (`rrc_reasoning`).
After your opening, a FULL virtual-bargaining deliberation (simulating what the
stakeholders would agree to) will be appended verbatim -- you do NOT write that part.

Your job: produce a 1-3 sentence FIRST-PERSON procedure-selection preamble that
explains why, for THIS case, I will simulate rational bargaining among the
stakeholders instead of applying a simple heuristic rule.

- If `rrc_reasoning` chose virtual bargaining (it discusses simulating
  stakeholders / bargaining / negotiation), extract and lightly paraphrase ONLY
  its justification for choosing bargaining over rules -- the part about high
  stakes / the situation being unusual. mode = "splice".
- If `rrc_reasoning` instead applied a rule (no bargaining), write a fresh
  justification grounded in THIS story's specific stakes and unusualness for why
  bargaining is warranted. mode = "template".

Hard rules:
- First person ("I'll simulate what the stakeholders would agree to ...").
- End by committing to virtual bargaining.
- Do NOT include any stakeholder list, negotiation, or conclusion -- opening only.
- Do NOT state a YES/NO answer.
- Do NOT mention "the RRC spec", "step 2", "instructions", or a "prior trace".

Output a STRICT JSON array, one object per input row:
[{"id": "<id>", "mode": "splice"|"template", "preamble": "<1-3 sentences>"}]"""
